'use strict';
const crypto=require('node:crypto');
const repo=require('../repositories/transaction.repository');
const centres=require('../repositories/centre.repository');
const {appendAuditLog}=require('../repositories/audit.repository');
const {withTransaction}=require('../config/database');
const {TRANSACTION_TRANSITIONS}=require('../constants/states');
function error(code,message,status){return Object.assign(new Error(message),{code,status});}
function scaled(value,digits){const [whole,fraction='']=String(value).split('.');return BigInt(whole)*10n**BigInt(digits)+BigInt((fraction+'0'.repeat(digits)).slice(0,digits));}
function formatScaled(value,digits){const negative=value<0n;const raw=(negative?-value:value).toString().padStart(digits+1,'0');return `${negative?'-':''}${raw.slice(0,-digits)}.${raw.slice(-digits)}`;}
function calculatePurchase(acceptedQuantity,rate,deductionAmount='0'){const quantity=scaled(acceptedQuantity,3),rateCents=scaled(rate,2),deduction=scaled(deductionAmount,2);const gross=(quantity*rateCents+500n)/1000n;if(quantity<=0n||rateCents<=0n)throw error('INVALID_PURCHASE_VALUES','Accepted quantity and rate must be positive.',400);if(deduction<0n||deduction>gross)throw error('INVALID_DEDUCTION','Deduction cannot exceed the gross purchase value.',400);return{grossAmount:formatScaled(gross,2),totalAmount:formatScaled(gross-deduction,2)};}
async function assertScope(actor,centreId,connection){if(actor.role==='admin')return;if(!await centres.isOfficerAssigned(actor.userId,centreId,connection))throw error('CENTRE_FORBIDDEN','You are not assigned to this centre.',403);}
async function inspect(input,actor){return withTransaction(async connection=>{const context=await repo.contextForAppointment(input.appointmentId,connection,true);if(!context)throw error('APPOINTMENT_NOT_FOUND','Appointment not found.',404);await assertScope(actor,context.centre_id,connection);if(!['inspection','in_service'].includes(context.queue_status))throw error('INSPECTION_NOT_READY','The token must be in service or inspection.',409);let tx=await repo.findByAppointment(input.appointmentId,connection,true);if(!tx){const id=await repo.createTransaction({reference:`TX-${crypto.randomBytes(8).toString('hex').toUpperCase()}`,appointmentId:input.appointmentId,officerId:actor.userId},connection);tx=await repo.findById(id,connection,true);}else if(!['inspection_in_progress','on_hold'].includes(tx.transaction_status))throw error('INVALID_TRANSACTION_STATE','This inspection decision is already final.',409);const version=await repo.inspectionVersion(tx.transaction_id,connection);await repo.insertInspection({...input,transactionId:tx.transaction_id,version,actorId:actor.userId},connection);await appendAuditLog({actorId:actor.userId,action:'INSPECTION_RECORDED',entityType:'procurement_transaction',entityId:tx.transaction_id,before:{status:tx.transaction_status},after:{status:input.result,version,actualQuantity:input.actualQuantity},metadata:{notes:input.notes||null}},connection);return repo.findById(tx.transaction_id,connection);});}
async function purchase(transactionId,input,actor){return withTransaction(async connection=>{const existing=await repo.findPurchaseByKey(input.idempotencyKey,connection);if(existing){if(Number(existing.transaction_id)!==transactionId)throw error('IDEMPOTENCY_KEY_CONFLICT','This idempotency key belongs to another purchase.',409);return existing;}const tx=await repo.findById(transactionId,connection,true);if(!tx)throw error('TRANSACTION_NOT_FOUND','Transaction not found.',404);await assertScope(actor,tx.centre_id,connection);if(tx.transaction_status!=='accepted')throw error('INVALID_TRANSACTION_STATE','Only an accepted inspection can be purchased.',409);if(scaled(input.acceptedQuantity,3)>scaled(tx.actual_quantity,3))throw error('ACCEPTED_QUANTITY_EXCEEDS_ACTUAL','Accepted quantity cannot exceed verified actual quantity.',400);const amounts=calculatePurchase(input.acceptedQuantity,input.rate,input.deductionAmount);if(!await repo.recordPurchase(transactionId,input,amounts,connection))throw error('PURCHASE_CONFLICT','The transaction changed before purchase recording.',409);await repo.insertPayment(transactionId,{status:'pending',amount:amounts.totalAmount},actor.userId,connection);await repo.updateTransactionPaymentStatus(transactionId,'pending',connection);const after=await repo.findById(transactionId,connection);await appendAuditLog({actorId:actor.userId,action:'PURCHASE_RECORDED',entityType:'procurement_transaction',entityId:transactionId,before:tx,after},connection);return after;});}
async function payment(transactionId,input,actor){return withTransaction(async connection=>{const tx=await repo.findById(transactionId,connection,true);if(!tx)throw error('TRANSACTION_NOT_FOUND','Transaction not found.',404);await assertScope(actor,tx.centre_id,connection);const desired={pending:'payment_pending',initiated:'payment_initiated',completed:'payment_completed',failed:'payment_failed',unknown:'payment_pending'}[input.status];if(!(TRANSACTION_TRANSITIONS[tx.transaction_status]||[]).includes(desired)&&tx.transaction_status!==desired)throw error('INVALID_PAYMENT_TRANSITION',`Cannot record ${input.status} from ${tx.transaction_status}.`,409);if(scaled(input.amount,2)!==scaled(tx.total_amount,2))throw error('PAYMENT_AMOUNT_MISMATCH','Payment amount must match the recorded purchase total.',400);const paymentId=await repo.insertPayment(transactionId,input,actor.userId,connection);await repo.updateTransactionPaymentStatus(transactionId,input.status,connection);await appendAuditLog({actorId:actor.userId,action:'PAYMENT_STATUS_RECORDED',entityType:'payment_record',entityId:paymentId,before:{transactionStatus:tx.transaction_status},after:{status:input.status,verificationSource:input.verificationSource||null}},connection);return repo.findById(transactionId,connection);});}
async function correction(transactionId,input,actor){return withTransaction(async connection=>{const tx=await repo.findById(transactionId,connection,true);if(!tx)throw error('TRANSACTION_NOT_FOUND','Transaction not found.',404);await assertScope(actor,tx.centre_id,connection);if(!tx.accepted_quantity||!tx.rate)throw error('CORRECTION_NOT_AVAILABLE','A recorded purchase is required before correction.',409);const values={actualQuantity:input.actualQuantity||tx.actual_quantity,acceptedQuantity:input.acceptedQuantity||tx.accepted_quantity,rate:input.rate||tx.rate,deductionAmount:input.deductionAmount||tx.deduction_amount};if(scaled(values.acceptedQuantity,3)>scaled(values.actualQuantity,3))throw error('ACCEPTED_QUANTITY_EXCEEDS_ACTUAL','Accepted quantity cannot exceed actual quantity.',400);const amounts=calculatePurchase(values.acceptedQuantity,values.rate,values.deductionAmount);await repo.correct(transactionId,input,amounts,connection);const after=await repo.findById(transactionId,connection);await repo.insertAmendment(transactionId,tx,after,input.reason,actor.userId,connection);await appendAuditLog({actorId:actor.userId,action:'TRANSACTION_CORRECTED',entityType:'procurement_transaction',entityId:transactionId,before:tx,after,metadata:{reason:input.reason}},connection);return after;});}
async function mine(userId){return repo.historyForFarmer(userId);}
async function centreHistory(centreId,actor){await assertScope(actor,centreId);return repo.historyForCentre(centreId);}
module.exports={inspect,purchase,payment,correction,mine,centreHistory,calculatePurchase,scaled,formatScaled};
