import { t } from '../js/i18n.js';
import { api, download } from '../js/api-client.js';
import { loadingState, emptyState, errorState } from '../components/data-state.js';
let chart;
const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const now=new Date(),monthAgo=new Date(Date.now()-30*86400000);const date=v=>v.toISOString().slice(0,10);
export function analyticsPage(){return`<div class="page-shell"><div class="page-heading"><div><p class="eyebrow">${t('analytics')}</p><h1>${t('operationalAnalytics')}</h1><p>${t('operationalAnalyticsHelp')}</p></div><div><button class="button secondary" data-export="csv">CSV</button> <button class="button secondary" data-export="pdf">PDF</button></div></div><form class="filter-bar" data-analytics-filter><label class="field">${t('procurementDate')}<input type="date" name="dateFrom" value="${date(monthAgo)}" required></label><label class="field">${t('procurementDate')}<input type="date" name="dateTo" value="${date(now)}" required></label><label class="field">${t('centres')}<select name="centreId"><option value="">${t('allDistricts')}</option></select></label><label class="field">${t('allCrops')}<select name="cropId"><option value="">${t('allCrops')}</option></select></label><button class="button primary">${t('view')}</button></form><div data-analytics-results>${loadingState()}</div></div>`;}
function query(form){const p=new URLSearchParams();for(const [k,v]of new FormData(form))if(v)p.set(k,v);return p.toString();}
async function render(form){const target=document.querySelector('[data-analytics-results]');target.innerHTML=loadingState();try{const data=await api(`/analytics?${query(form)}`),s=data.summary;if(!data.series.length){target.innerHTML=emptyState();return;}target.innerHTML=`<div class="metric-grid">${[['appointments',s.appointments],['completionRate',`${s.completionRate}%`],['averageWaitMinutes',s.averageWaitMinutes??'—'],['capacityUtilisation',`${s.capacityUtilisation}%`],['procuredQuantity',s.procuredQuantity],['purchaseValue',`₹${s.purchaseValue}`]].map(([k,v])=>`<article class="card metric"><span>${t(k)}</span><strong>${safe(v)}</strong></article>`).join('')}</div><article class="card chart-card"><canvas data-analytics-chart></canvas></article>`;if(!window.Chart)throw new Error('Chart library is unavailable.');chart?.destroy();chart=new window.Chart(target.querySelector('canvas'),{type:'bar',data:{labels:data.series.map(x=>String(x.metric_date).slice(0,10)),datasets:[{label:t('appointments'),data:data.series.map(x=>x.appointments),backgroundColor:'#21865d'},{label:t('completed'),data:data.series.map(x=>x.completed),backgroundColor:'#e1a72f'}]},options:{responsive:true,maintainAspectRatio:false}});}catch(e){target.innerHTML=errorState(e.message);}}
export async function loadAnalytics(){const form=document.querySelector('[data-analytics-filter]');if(!form)return;try{const [centres,crops]=await Promise.all([api('/centres'),api('/crops')]);form.centreId.insertAdjacentHTML('beforeend',centres.map(x=>`<option value="${x.centre_id}">${safe(x.centre_name)}</option>`).join(''));form.cropId.insertAdjacentHTML('beforeend',crops.map(x=>`<option value="${x.crop_id}">${safe(x.crop_name_en)}</option>`).join(''));}catch{}form.addEventListener('submit',e=>{e.preventDefault();render(form);});document.querySelectorAll('[data-export]').forEach(b=>b.addEventListener('click',()=>download(`/analytics/export.${b.dataset.export}?${query(form)}`,`agriprocure-report.${b.dataset.export}`)));render(form);}
