import { t, getLocale } from '../js/i18n.js';
import { api, post, patch, getAccessToken } from '../js/api-client.js';
import { loadingState, emptyState, errorState } from '../components/data-state.js';
import { statusBadge } from '../components/status-badge.js';
let user;
const today = () => new Date().toISOString().slice(0, 10);
const safe = (value) => String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[c]));
export function queuePage(currentUser) {
  user = currentUser;
  const controls = currentUser.role === 'farmer' ? '' : `<form class="filter-bar" data-queue-filter><label class="field">${t('centres')}<select name="centreId" required></select></label><label class="field">${t('procurementDate')}<input name="date" type="date" value="${today()}" required></label><button class="button secondary">${t('view')}</button></form><div class="queue-actions" data-queue-actions hidden><button class="button primary" data-next-token>${t('callNext')}</button><button class="button secondary" data-queue-state="running">${t('resumeQueue')}</button><button class="button secondary" data-queue-state="paused">${t('pauseQueue')}</button></div>`;
  return `<div class="page-shell"><div class="page-heading"><div><p class="eyebrow">${t('queue')}</p><h1>${t('followQueue')}</h1><p>${t('followQueueHelp')}</p></div></div>${controls}<div data-queue-results>${loadingState()}</div></div>`;
}
function farmerRows(items) {
  if (!items.length) return emptyState();
  return `<div class="booking-list">${items.map((x) => `<article class="card queue-card"><div class="centre-card-title"><h2>${safe(x.token_number)}</h2>${statusBadge(safe(x.queue_status.replaceAll('_',' ')))}</div><p>${safe(x.centre_name)} · ${safe(getLocale()==='hi'?x.crop_name_hi:x.crop_name_en)}</p><dl><div><dt>${t('farmersAhead')}</dt><dd>${safe(x.farmers_ahead)}</dd></div><div><dt>${t('estimatedWait')}</dt><dd>${x.estimated_wait_minutes == null ? t('queuePaused') : `${safe(x.estimated_wait_minutes)} ${t('minutes')}`}</dd></div><div><dt>${t('lastUpdated')}</dt><dd>${new Date(x.estimate_updated_at).toLocaleTimeString()}</dd></div></dl>${x.queue_status==='not_checked_in'?`<button class="button primary" data-check-in="${x.appointment_id}">${t('checkIn')}</button>`:''}${['waiting','called'].includes(x.queue_status)?`<button class="button secondary" data-predict-wait="${x.token_id}">${t('predictWait')}</button><p data-wait-result="${x.token_id}"></p>`:''}</article>`).join('')}</div>`;
}
function operatorRows(data) {
  if (!data.tokens.length) return emptyState();
  return `<div class="table-wrap"><table><thead><tr><th>${t('token')}</th><th>${t('farmer')}</th><th>${t('appointmentStatus')}</th><th>${t('lastUpdated')}</th><th></th></tr></thead><tbody>${data.tokens.map((x) => `<tr><td>${safe(x.token_number)}</td><td>${safe(x.farmer_name)}</td><td>${statusBadge(safe(x.queue_status.replaceAll('_',' ')))}</td><td>${new Date(x.updated_at).toLocaleTimeString()}</td><td>${x.queue_status==='called'?`<button class="button secondary" data-transition="${x.token_id}" data-status="in_service">${t('startService')}</button>`:''}${x.queue_status==='in_service'?`<button class="button secondary" data-transition="${x.token_id}" data-status="inspection">${t('startInspection')}</button>`:''}${x.queue_status==='inspection'?`<button class="button primary" data-inspect="${x.appointment_id}">${t('recordInspection')}</button>`:''}${['in_service','inspection'].includes(x.queue_status)?`<button class="button secondary" data-transition="${x.token_id}" data-status="completed">${t('complete')}</button>`:''}${x.queue_status==='called'?`<button class="button ghost danger" data-transition="${x.token_id}" data-status="no_show">${t('noShow')}</button>`:''}</td></tr>`).join('')}</tbody></table></div><section data-transaction-results></section>`;
}
function transactionRows(items,input){const target=document.querySelector('[data-transaction-results]');if(!target)return;target.innerHTML=`<h2>${t('trackProcurement')}</h2>${items.length?`<div class="booking-list">${items.map(x=>`<article class="card"><div class="centre-card-title"><strong>${safe(x.transaction_reference)}</strong>${statusBadge(safe(x.transaction_status.replaceAll('_',' ')))}</div><p>${safe(x.farmer_name)} · ${safe(x.actual_quantity||'—')} ${t('quintals')}</p><p>${x.total_amount?`₹${safe(x.total_amount)}`:''}</p>${x.transaction_status==='accepted'?`<button class="button primary" data-purchase="${x.transaction_id}">${t('recordPurchase')}</button>`:''}${['payment_pending','payment_initiated','payment_failed'].includes(x.transaction_status)?`<button class="button secondary" data-payment="${x.transaction_id}" data-amount="${x.total_amount}">${t('recordPayment')}</button>`:''}</article>`).join('')}</div>`:emptyState()}`;target.querySelectorAll('[data-purchase]').forEach(b=>b.addEventListener('click',async()=>{const acceptedQuantity=prompt(t('acceptedQuantity'));const rate=prompt(t('authorisedRate'));if(!acceptedQuantity||!rate)return;await post(`/transactions/${b.dataset.purchase}/purchase`,{acceptedQuantity,rate,deductionAmount:'0',idempotencyKey:crypto.randomUUID()});await loadOperator(input);}));target.querySelectorAll('[data-payment]').forEach(b=>b.addEventListener('click',async()=>{const status=prompt(`${t('paymentStatus')}: initiated, completed, failed`,'initiated');if(!status)return;const body={status,amount:b.dataset.amount};if(status==='completed'){body.verificationSource=prompt(t('verificationSource'));body.providerReference=prompt(t('providerReference'));if(!body.verificationSource||!body.providerReference)return;}await post(`/transactions/${b.dataset.payment}/payments`,body);await loadOperator(input);}));}
function subscribe(centreId, date, reload) {
  if (!window.io) return;
  const socket = window.io({ auth: { token: getAccessToken() } });
  socket.emit('queue:subscribe', { centreId, date }, (result) => { if (!result?.ok) socket.disconnect(); });
  socket.on('queue:update', reload);
}
async function loadFarmer() {
  const target=document.querySelector('[data-queue-results]');
  try { const items=await api('/queue/my'); target.innerHTML=farmerRows(items); target.querySelectorAll('[data-check-in]').forEach((b)=>b.addEventListener('click',async()=>{try{await post('/queue/check-in',{appointmentId:b.dataset.checkIn}); await loadFarmer();}catch(e){target.innerHTML=errorState(e.message);}}));target.querySelectorAll('[data-predict-wait]').forEach(b=>b.addEventListener('click',async()=>{try{const p=await post(`/predictions/waiting/${b.dataset.predictWait}`,{});target.querySelector(`[data-wait-result="${b.dataset.predictWait}"]`).textContent=`${p.value} ${t('minutes')} (${p.lower_bound}–${p.upper_bound}) · ${p.method==='model'?t('modelPrediction'):t('fallbackEstimate')}`;}catch(e){window.dispatchEvent(new CustomEvent('agriprocure:toast',{detail:e.message}));}})); if(items[0]) subscribe(items[0].centre_id,String(items[0].queue_date).slice(0,10),loadFarmer); }
  catch(e){ target.innerHTML=errorState(e.message); }
}
async function loadOperator(input) {
  const target=document.querySelector('[data-queue-results]'); target.innerHTML=loadingState();
  try { const data=await api(`/queue?centreId=${encodeURIComponent(input.centreId)}&date=${input.date}`); target.innerHTML=operatorRows(data); document.querySelector('[data-queue-actions]').hidden=false; target.querySelectorAll('[data-transition]').forEach((b)=>b.addEventListener('click',async()=>{const reason=b.dataset.status==='no_show'?(prompt(t('noShowReason'))||'Not present when called'):undefined; await patch(`/queue/tokens/${b.dataset.transition}`,{status:b.dataset.status,reason}); await loadOperator(input);}));target.querySelectorAll('[data-inspect]').forEach(b=>b.addEventListener('click',async()=>{const result=prompt(`${t('inspectionDecision')}: accepted, rejected, on_hold`,'accepted');const actualQuantity=prompt(t('actualQuantity'));if(!result||!actualQuantity)return;const notes=result==='accepted'?undefined:prompt(t('decisionReason'));await post('/transactions/inspections',{appointmentId:b.dataset.inspect,result,actualQuantity,notes});await loadOperator(input);}));transactionRows(await api(`/transactions?centreId=${encodeURIComponent(input.centreId)}`),input); subscribe(input.centreId,input.date,()=>loadOperator(input)); }
  catch(e){target.innerHTML=errorState(e.message);}
}
export async function loadQueue() {
  if(user.role==='farmer') return loadFarmer();
  const centres=await api('/centres'); const form=document.querySelector('[data-queue-filter]'); form.centreId.innerHTML=centres.map((c)=>`<option value="${c.centre_id}">${safe(c.centre_name)}</option>`).join('');
  const values=()=>Object.fromEntries(new FormData(form)); form.addEventListener('submit',(e)=>{e.preventDefault();loadOperator(values());});
  document.querySelector('[data-next-token]').addEventListener('click',async()=>{await post('/queue/next',values());await loadOperator(values());});
  document.querySelectorAll('[data-queue-state]').forEach((b)=>b.addEventListener('click',async()=>{const v=values();await api('/queue/control',{method:'PUT',body:JSON.stringify({...v,state:b.dataset.queueState,activeCounters:1,reason:b.dataset.queueState==='paused'?'Operator pause':undefined})});await loadOperator(v);}));
  if(centres[0]) loadOperator(values()); else document.querySelector('[data-queue-results]').innerHTML=emptyState();
}
